apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-access-eks
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
 name: azure-access-eks
 annotations:
   kubernetes.io/service-account.name: azure-access-eks
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: permission-to-CICD
  namespace: default
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: permission-to-CICD-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: permission-to-CICD
subjects:
- kind: ServiceAccount
  name: azure-access-eks
  namespace: default
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permission-to-CICD-CR
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: permission-to-CICD-CR-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: permission-to-CICD-CR
subjects:
- kind: ServiceAccount
  name: azure-access-eks
  namespace: default