apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  labels:
    app.kubernetes.io/name: vault
spec:
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  publishNotReadyAddresses: true
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8200
