---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-app
---
apiVersion: v1
kind: Secret
metadata:
 name: web-app
 annotations:
   kubernetes.io/service-account.name: web-app
type: kubernetes.io/service-account-token
