apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/agent-cache-enable: "true"
          vault.hashicorp.com/role: "web-app"
          vault.hashicorp.com/agent-inject-secret-database-connect: "database/creds/readonly"
          vault.hashicorp.com/agent-inject-template-database-connect: |
            {{- with secret "database/creds/readonly" -}}

            USRNAME={{ .Data.username }}  PASSWORD={{ .Data.password }}  HOST=mysql  DATABASE=newdb 
            
            {{- end -}}
    spec:
      serviceAccountName: web-app
      containers:
      - name: web-app
        image: 297289183593.dkr.ecr.eu-west-1.amazonaws.com/onboardnodejs:latest
        args:
             ['sh','-c',' chmod 444 /vault/secrets/database-connect  && export $(cat /vault/secrets/database-connect) && node /nodeapp/app.js ']
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
