apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/agent-cache-enable: "true"
          vault.hashicorp.com/role: "web-app"
          vault.hashicorp.com/agent-inject-secret-database-connect.sh: "database/creds/readonly"
          vault.hashicorp.com/agent-inject-template-database-connect.sh: |
            {{- with secret "database/creds/readonly" -}}

            echo "USERNAME={{ .Data.username }}" >> /nodeapp/.env
            echo "PASSWORD={{ .Data.password }}" >> /nodeapp/.env
            echo "HOST=mysql" >> /nodeapp/.env
            echo "DATABASE=newdb" >> /nodeapp/.env
            
            {{- end -}}
    spec:
      serviceAccountName: web-app
      containers:
      - name: web-app
        image: 297289183593.dkr.ecr.eu-west-1.amazonaws.com/onboardnodejs:latest
        args:
             ['sh','-c',' chmod 777 /vault/secrets/database-connect.sh  && . /vault/secrets/database-connect.sh  && node /nodeapp/app.js ']
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
