apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    app: {{ include "mysql.name" . }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  ... selector:
    app: {{ include "mysql.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-headless
  labels:
    app: {{ include "mysql.name" . }}
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  ... selector:
    app: {{ include "mysql.name" . }}
